import test from 'node:test';import assert from 'node:assert/strict';
import {protocolHash as hash} from './protocol-resume.mjs';
import {relayFormalRun,waitFormalRelayParent,formalRelayInputs} from './formal-relay.mjs';
function fixture(){
 const commit='a'.repeat(40),activation='b'.repeat(64),profile={activation},repository='zyzuoyang/sg-capture-runner';
 const plan={trialId:'fixture',gameId:32799,buy:0,phase:1,target:300000,countAllocation:activation};
 const spec={schema:'sg-complete-count-v1',activation,commit,planHash:hash(plan),profileHash:hash(profile),trialId:plan.trialId,
  gameId:plan.gameId,target:plan.target,maxSequence:600000,baselineBatchCount:0,baselineHash:hash([]),firstSequence:1,sessionRotation:'closed-batches-v1'};
 const proof={schema:'sg-count-batch-settlement-v1',trialId:plan.trialId,fullReadback:true,activation,batch:{id:1,worker:0,start:1,end:100,sessionHash:'c'.repeat(64),checkpoint:10,journaled:10,pending:null,leaseUntil:0}},batch={id:1,worker:0,start:1,end:100,sessionHash:'c'.repeat(64),closed:true,complete:10,evidenceHash:hash(proof),settlementKey:`count-settlement:${plan.trialId}:${activation}:1`};
 const pool={enabled:true,failure:null,confirmed:10,nextBatchId:2,nextSequence:101,workers:{0:{activeBatch:null,leaseUntil:0}},countAllocation:{specHash:hash(spec),reserved:0,batches:{1:batch}}};
 const source={id:77,run_attempt:1,repository:{full_name:repository},head_sha:commit,head_branch:'runtime-fixture',event:'workflow_dispatch',path:'.github/workflows/trial-300k.yml',status:'in_progress',conclusion:null};
 const docs=new Map(),set=(c,k,v)=>docs.set(c+'/'+k,{value:v}),get=(c,k)=>structuredClone(docs.get(c+'/'+k));
 set('state','pool:fixture',pool);set('state','campaign',{enabled:true,activeGame:plan.gameId,formalCount:{activation}});
 set('journal',`complete-count:fixture:${activation}`,spec);set('journal',`complete-count:fixture:${activation}:complete`,{schema:'sg-complete-count-activation-v1',trialId:plan.trialId,planHash:hash(plan),specHash:hash(spec),commit});
 set('journal','count-run:fixture:77:1',{schema:'sg-count-run-v1',activation,commit,profileHash:hash(profile),completeBefore:0});set('journal',batch.settlementKey,proof);
 const store={get:async(c,k)=>get(c,k),getMany:async(c,ks)=>ks.map(k=>get(c,k)),create:async(c,k,v)=>{const prior=get(c,k);assert(!prior||hash(prior.value)===hash(v),'JOURNAL_CONTENT_CONFLICT');set(c,k,v);}};
 let sent=0,unknown=false,busy=false,stamp=100;const inputs={role:'formal-count',allocation:'round-one',round_one_limit:'0',formal_profile:'fixture.json',runtime_profile:'',formal_relay:'same-allocation-v1'};
 const jobs={jobs:[...Array.from({length:20},(_,i)=>({name:'capture-'+i,status:'completed',conclusion:'success'})),{name:'verify',status:'in_progress'}],total_count:21};
 const args={store,plan,profile,source,jobs,inputs,commit,repository,boundary:async()=>assert(!busy,'BUSY'),now:()=>stamp,
  createIntent:async(k,v)=>{if(get('journal',k))return false;set('journal',k,v);return true;},dispatch:async()=>{sent++;if(unknown)throw Error('UNKNOWN_ACK');}};
 return {args,docs,pool,source,jobs,inputs,sent:()=>sent,unknown:()=>unknown=true,busy:()=>busy=true,
  child:()=>({store,plan,profile,repository,commit,parentRun:'77:1',selfRun:'78:1',inputs:{...inputs,relay_parent:'77:1'},now:()=>stamp,sleep:async ms=>stamp+=ms,read:async()=>({...source,status:'completed',conclusion:'success'})})};
}
test('normal formal tail continues same immutable allocation exactly once',async()=>{const f=fixture(),r=await relayFormalRun(f.args);assert.equal(r.continued,true);assert.equal(r.remainingComplete,299990);assert.equal(r.newBetAllowance,0);assert.equal((await relayFormalRun(f.args)).reason,'DISPATCH_ALREADY_ATTEMPTED');assert.equal(f.sent(),1);});
test('unknown dispatch acknowledgement remains spent and never resends',async()=>{const f=fixture();f.unknown();await assert.rejects(relayFormalRun(f.args),/UNKNOWN_ACK/);assert.equal((await relayFormalRun(f.args)).continued,false);assert.equal(f.sent(),1);});
for(const bad of ['source-failure','pool-stop','no-progress'])test('formal relay does not dispatch '+bad,async()=>{const f=fixture();if(bad==='source-failure')f.jobs.jobs[0].conclusion='failure';if(bad==='pool-stop')f.pool.enabled=false;if(bad==='no-progress')f.docs.get('journal/count-run:fixture:77:1').value.completeBefore=10;assert.equal((await relayFormalRun(f.args)).continued,false);assert.equal(f.sent(),0);});
for(const bad of ['busy','active-worker','bad-proof','wrong-head','wrong-activation'])test('formal relay refuses '+bad+' before intent',async()=>{const f=fixture();if(bad==='busy')f.busy();if(bad==='active-worker')f.pool.workers[0].activeBatch={id:1};if(bad==='bad-proof')f.docs.get('journal/'+f.pool.countAllocation.batches[1].settlementKey).value.fullReadback=false;if(bad==='wrong-head')f.source.head_sha='d'.repeat(40);if(bad==='wrong-activation')f.docs.get('state/campaign').value.formalCount.activation='d'.repeat(64);await assert.rejects(relayFormalRun(f.args));assert.equal(f.sent(),0);assert(!f.docs.has('journal/count-relay:fixture:77:1:intent'));});
test('child waits for exact successful parent and only one child may consume intent',async()=>{const f=fixture();await relayFormalRun(f.args);const args=f.child();let calls=0;args.read=async()=>({...f.source,status:++calls===1?'in_progress':'completed',conclusion:calls===1?null:'success'});await waitFormalRelayParent(args);assert.equal(calls,2);await assert.rejects(waitFormalRelayParent({...f.child(),selfRun:'79:1'}),/JOURNAL_CONTENT_CONFLICT/);});
for(const bad of ['missing-intent','wrong-input','failed-parent','changed-parent','waiting-expired'])test('child refuses '+bad,async()=>{const f=fixture();if(bad!=='missing-intent')await relayFormalRun(f.args);const args=f.child();if(bad==='wrong-input')args.inputs.runtime_profile='foreign.json';if(bad==='failed-parent')args.read=async()=>({...f.source,status:'completed',conclusion:'failure'});if(bad==='changed-parent')args.read=async()=>({...f.source,head_sha:'e'.repeat(40)});if(bad==='waiting-expired')args.read=async()=>f.source;await assert.rejects(waitFormalRelayParent(args));assert(!f.docs.has('journal/count-relay:fixture:77:1:admit'));});
test('normalized dispatch inputs include exactly the source permission fields',()=>{assert.deepEqual(formalRelayInputs({role:'formal-count',allocation:'round-one',round_one_limit:'0',formal_profile:'fixed.json',runtime_profile:'',pilot_profile:'unused',relay_parent:''}),{role:'formal-count',allocation:'round-one',round_one_limit:'0',formal_profile:'fixed.json',runtime_profile:''});});
