// Portable synthetic control fixture. Parser is a test double; no official data.
import test from 'node:test';import assert from 'node:assert/strict';
import {retireDemoPool} from './retire-demo-pool.mjs';import {protocolHash as hash} from './protocol-resume.mjs';import {receiptKey} from './durable-queue.mjs';
function fixture(){
 const plan={trialId:'synthetic-demo',gameId:32820,phase:1,buy:0},pool={enabled:false,nextBatchId:2,workers:{7:{leaseUntil:0}}},pending={sequence:3,attempt:'unfinished',awaiting:null,raw:{steps:[{msgId:'BET'}]}};
 pool.planHash=hash(plan);
 const batch={id:1,worker:7,start:1,end:100,epoch:0,leaseUntil:0,checkpoint:0,journaled:2,sessionHash:'session',pending,failure:'PROTOCOL_VALIDATION_FAILED'};
 const docs=new Map([['state/pool:'+plan.trialId,{value:pool}],['state/batch:'+plan.trialId+':1',{value:batch}],['state/write-permits',{value:{limit:1,slots:{}}}]]),mongo=new Map();let failAt=null,corrupt=false,busy=false;
 for(let n=1;n<=2;n++){const r={_id:hash('r'+n),contentHash:hash('content'+n),trialId:plan.trialId,batchId:1,shardId:7,sequence:n,sourceSessionHash:'session',fixtureOnly:false,buy:0,raw:{synthetic:true}};docs.set('journal/'+receiptKey(plan.trialId,n),{value:r});}
 const get=(c,k)=>structuredClone(docs.get(c+'/'+k));const store={get:async(c,k)=>get(c,k),getMany:async(c,keys)=>keys.map(k=>get(c,k)),writable:async()=>{},create:async(c,k,v)=>{assert(!docs.has(c+'/'+k));assert(k!==failAt,'INJECTED_FAILURE');docs.set(c+'/'+k,{value:structuredClone(v)});},update:async(c,k,fn)=>{const v=fn(get(c,k).value);if(v!==null)docs.set(c+'/'+k,{value:v});return get(c,k);}};
 const transport={request:async(op,p)=>{if(op==='rounds_insert'){for(const r of p.records)mongo.set(r._id,structuredClone(r));return {};}assert.equal(op,'rounds_read');const a=[...mongo.values()].filter(r=>p.ids.includes(r._id)).map(x=>structuredClone(x));if(corrupt&&a.length)a[0].sequence=999;return a;}};
 const args={store,transport,plan,parser:{call:async({record})=>({verified:record.raw.synthetic===true})},gate:{status:()=>({allowed:true,maxBatchSize:100}),hold(){}},boundary:async()=>assert(!busy,'BUSY'),owner:'test',now:()=>100,expectedPoolHash:hash(pool)};
 return {args,docs,mongo,get,fail:k=>failAt=k,corrupt:()=>corrupt=true,busy:()=>busy=true,batch};
}
test('flush completed records, archive interrupted attempt and remove active partial without a source grant',async()=>{const f=fixture(),r=await retireDemoPool(f.args);assert.equal(r.completePreserved,2);assert.equal(r.abandonedAttempts,1);assert.equal(f.mongo.size,2);const b=f.get('state','batch:synthetic-demo:1').value;assert.equal(b.checkpoint,2);assert.equal(b.pending,null);assert.equal(r.sourceRequests,0);assert.equal(r.newBetAllowance,0);assert.equal(f.get('state','pool:synthetic-demo').value.enabled,false);assert(![...f.docs.keys()].some(k=>k.includes('protocol-resume:')));await assert.rejects(retireDemoPool(f.args),/POOL_CHANGED/);});
test('unknown response is explicitly abandoned, never represented as successful or never-sent',async()=>{const f=fixture();f.batch.pending.awaiting='BET payload';await retireDemoPool(f.args);const archive=[...f.docs.entries()].find(([k])=>k.endsWith(':analysis'))[1].value;assert.equal(archive.attempts[0].disposition,'unknown-abandoned-without-replay');assert.equal(archive.attempts[0].pending.awaiting,'BET payload');});
test('incomplete archive preserves active pending and refuses blind rerun',async()=>{const f=fixture();f.fail('retired-demo:synthetic-demo:'+f.args.expectedPoolHash.slice(0,16)+':analysis');await assert.rejects(retireDemoPool(f.args),/INJECTED/);assert(f.get('state','batch:synthetic-demo:1').value.pending);assert.equal(f.mongo.size,0);await assert.rejects(retireDemoPool(f.args),/ALREADY_STARTED/);});
test('Mongo conflict does not erase pending or advance checkpoint',async()=>{const f=fixture();f.corrupt();await assert.rejects(retireDemoPool(f.args),/MONGO_CONTENT_CONFLICT/);const b=f.get('state','batch:synthetic-demo:1').value;assert(b.pending);assert.equal(b.checkpoint,0);});
test('active boundary refuses before archival or mutation',async()=>{const f=fixture();f.busy();const old=hash([...f.docs]);await assert.rejects(retireDemoPool(f.args),/BUSY/);assert.equal(hash([...f.docs]),old);});
test('already settled historical batch retains the exact generation audit hash',async()=>{const f=fixture();f.batch.pending=null;f.batch.checkpoint=2;f.batch.retiredDemo='earlier-generation';for(const [k,r] of f.docs)if(k.startsWith('journal/receipt:'))f.mongo.set(r.value._id,r.value);const before=hash(f.batch);const r=await retireDemoPool(f.args);assert.equal(r.abandonedAttempts,0);assert.equal(hash(f.get('state','batch:synthetic-demo:1').value),before);});
